server:
  servlet:
    context-path: /myblog



mybatis:
  type-aliases-package: cn.hairui.blog.model
  mapper-locations: classpath:cn.hairui.blog.mapper/*.xml
  configuration:
    #配置mybatis支持驼峰命名 例如：表中user_name 映射类userName
    map-underscore-to-camel-case: true
